spring:
  #h2 Database
  datasource:
    url: jdbc:h2:tcp://localhost/~/mogak
    driver-class-name: org.h2.Driver
    username: root
    password: mogak1234!

  devtools:
    livereload:
      enabled: true

  jpa:
    database: sql_server
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: #파일 저장 경로
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false